### ISSUE TITLE
No channels appear

### ISSUE THREAD

**Issue by kamarul61** [weareblahs/epg#1]
I have put the link in pvr but no channels are appear...please help...

**Comment by weareblahs** [comment]
Now updating

**Comment by weareblahs** [comment]
Right now there is an error on my side, which it can't update (can't find Astro channels), saying "No Shows in Indexpage". You might have to wait until I reply when I fix this problem.

**Comment by weareblahs** [comment]
UPDATE: I found the error and now it's updating.

**Comment by weareblahs** [comment]
And remember to follow the steps (as shown at https://weareblahs.github.io/epg/ - How to Use) to update your playlist file for IPTV (m3u8).

Please note that this is just only EPG (Channel Guide) and doesn't provide sources for Live TV. You might have to find the source by yourself.
