### ISSUE TITLE
Possible to create Singapore Channel epg with episode date? 

### ISSUE THREAD

**Issue by bpsimm** [weareblahs/epg#10]
Hi, I'm Malaysian working in Singapore.

Been following and using your epg for a while. For some channel I found online. 

I am currently using HD Home Run to watch Singapore Local Channel online. I am using webgrabplus + Plex to do DVR for night news.

I have issue that the epg I created, unable to add episode number / episode date. This make Plex assume all different date show are same.

**Comment by bpsimm** [comment]
Is it possible a expert here can help me to edit the ini to show like this
![584fa613b7abdcb5ed029a9c05f6967d4602958b](https://user-images.githubusercontent.com/83934743/135985556-c4b76b29-9bef-46e7-b803-11c18dbd74fd.png)

Epg file:
https://pastebin.com/sw8yVqiL

Ini of Singapore (Singtel) :
http://webgrabplus.com/sites/default/files/download/ini/info/siteini.pack/Singapore/singteltv.com.sg.ini

**Comment by weareblahs** [comment]
This option is not present on the original site that it wants to grab, so there's no way to get it.
