### ISSUE TITLE
UnifiTV EPG not updated for a while

### ISSUE THREAD

**Issue by linkinstreet** [weareblahs/epg#12]
Hi, I noticed that the UnifiTV EPG is not update for a while now. The one that is currently in the git also has some error in terms of opening/closing tags, so that might be the reason why

**Comment by weareblahs** [comment]
Will be deleting the unifitv.xml file at and will renew it at the next
update. WebGrab also detects the tag problem and it refuses to update.

**Comment by weareblahs** [comment]
Should be fixed right now.
