### ISSUE TITLE
EPGs no longer working

### ISSUE THREAD

**Issue by aseanic** [weareblahs/epg#16]
https://weareblahs.github.io/epg/astro.xml (not updated)
https://weareblahs.github.io/epg/astro.xml.gz (fail not found)

**Comment by weareblahs** [comment]
Forgot to update this weekend. Will update soon.

**Comment by weareblahs** [comment]
UPDATE: Seems that I updated yesterday but there's a problem in GitHub pages. Will try to fix soon.

**Comment by weareblahs** [comment]
UPDATE: Fixed. Try refreshing it again.
