### ISSUE TITLE
Chinese channel for EPG working?

### ISSUE THREAD

**Issue by aa6my** [weareblahs/epg#2]
Hi, weareblahs

Im notice xml for chinese category`Astro` got bug.
![image](https://user-images.githubusercontent.com/7272163/118349740-1dca3100-b585-11eb-8c92-66508442de13.png)

`programme start="20210516000000`

just jump straight tp

`<programme start="20210518000000`

because of this causing program start & end 1 hour only daily.

![image](https://user-images.githubusercontent.com/7272163/118349811-9f21c380-b585-11eb-9202-5471433775d0.png)

**Comment by weareblahs** [comment]
A result for the Chinese Channel returns that the EPG is multilingual. 

Here's one of the examples of the API (This example uses Astro Shuang Xing, Ch 307 / ID: 183):

`` {
      "eventID": "36854541",
      "channelId": 183,
      "channelStbNumber": "307",
      "channelHD": "true",
      "channelTitle": "Astro Shuang Xing HD",
      "epgEventImage": null,
      "certification": "P13",
      "displayDateTimeUtc": "2021-05-14 16:00:00.0",
      "displayDateTime": "2021-05-15 00:00:00.0",
      "displayDuration": "01:00:00",
      "siTrafficKey": "1:10000171:43581665",
      "programmeTitle": "You Are My Hero Ep30",
      "programmeId": "JSCSN",
      "episodeId": "JSCTQ",
      "shortSynopsis": "Newly recruited resident doctor Mi Ka and special op Xing Ke Lei falls in love despite their differences as they face emergency crises during work.",
      "longSynopsis": null,
      "actors": "Ma Si Chun ,Bai Jing Ting",
      "directors": "Zhang Tong",
      "producers": "",
      "genre": "TV Show",
      "subGenre": "Series",
      "live": false,
      "premier": false,
      "ottBlackout": false,
      "highlight": null,
      "contentId": 37761,
      "contentImage": [],
      "groupKey": 20053865,
      "vernacularData": [
        {
          "vernacularLanguage": "zh",
          "vernacularProgrammeTitle": "你是我的城池营垒",
          "vernacularShortSynopsis": "当距离危险与死亡只有一步之遥，他们要如何守护这座城池和彼此?叙述新晋医生米佧在医院联合警校组织的应急救援演练中，和特警精英邢克垒相识，两人从冤家到相恋的浪漫爱情故事。",
          "vernacularLongSynopsis": "这部改编自同名小说的都市军旅情感剧，故事背景设定在医院联合特警队组织的应急救援培训中。讲述新晋医生米佧因工作结识了特警精英邢克垒，两人从一开始的互相误解到最后成为彼此的好搭档，期间他们也因地震被派往灾区实施救援，一同经历了诸多惊心动魄的事。最后，他们到底能否在救援的过程中一起坚守初心，并以各自的方式守护社会与人民的安宁幸福?",
          "actors": "马思纯 ,白敬亭",
          "directors": "张彤",
          "producers": ""
        }``

I will make a config file for the Chinese channels soon (multilingual).

(Note that this also applies to Tamil Channels, for example Astro Vaanavil.)

**Comment by aa6my** [comment]
btw thanks @weareblahs . Anything just inform me if u need configuration for infra `AWS` / `ALIBABA`

**Comment by aa6my** [comment]
@weareblahs after trying & trying it works using this
```
**------------------------------------------------------------------------------------------------
* @header_start
* WebGrab+Plus ini for grabbing EPG data from TvGuide websites
* @Site: astro.com.my
* @MinSWversion: V1.57
*
* @Revision 6 - [30/02/2017] Blackbear199
*   - api change
* @Revision 5 - [24/02/2017] Blackbear199
*   - api change
* @Revision 4 - [01/09/2016] Blackbear199
*   - api change
* @Revision 3 - [29/07/2016] Blackbear199
*   - rewrite
* @Revision 2 - [14/07/2016] Blackbear199
*   - fix title scrub so shows with (D),(L),ect at beginning dont get skipped
* @Revision 1 - [01/03/2016] Jan van Straaten
*   - maintenance revision
* @Revision 0 - [09/04/2013] Jan van Straaten
*   - creation
* @Remarks: your_remarks
* @header_end
**------------------------------------------------------------------------------------------------
site {url=astro.com.my|timezone=Asia/Kuala_Lumpur|maxdays=7|cultureinfo=en-GB|charset=UTF-8|titlematchfactor=90|episodesystem=xmltv_ns}
url_index{url|http://ams-api.astro.com.my/ams/v3/getEvents?periodStart=|urldate|:00:00:00&periodEnd=|urldate|:23:59:59&channelId=|channel|}
url_index.headers {customheader=Accept-Encoding=gzip,deflate}
urldate.format {datestring|yyy-MM-dd}
index_showsplit.scrub {regex||\{"eventID":.*?\]\},||}
index_start.scrub {regex||"displayDateTime":".*?(\d+:\d+:\d+)\.\d+||}
index_duration.scrub {regex||"displayDuration":"(\d+:\d+):\d+||}
index_title.scrub {single|"programmeTitle":"||","}
index_description.scrub {single|"shortSynopsis":"||","}
index_category.scrub {single|"genre":"||","}
index_category.scrub {single|"subGenre":"||","}
index_actor.scrub {single(separator=",")|"actors":"||","}
index_director.scrub {single(separator=",")|"directors":"||","}
index_producer.scrub {single|(separator=",")|"producers":"||","}
index_showicon.scrub {single|"epgEventImage":"||","}
index_episode.modify {substring(type=regex pattern="'S1' Ep'E1'""Ep'E1'")|'index_title' "S\d+\sEp\d+\|Ep\d+"}
index_title.modify {remove(type=regex)|\sS\d+\sEp\d+\|\sEp\d+}
end_scope

  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _  _
      #####  CHANNEL FILE CREATION (only to create the xxx-channel.xml file)
** @auto_xml_channel_start
* url_index{url|http://ams-api.astro.com.my/ams/v3/getChannels}
* index_site_id.scrub {multi|"channelId":||,"}
* index_site_channel.scrub {multi|channelTitle":"||",}
* index_site_id.modify {cleanup(removeduplicates=equal,100 link="index_site_channel")}
** @auto_xml_channel_end
```

`OUTPUT` - right now time 15:05 GMT+8

``` 
  <programme start="20210515151400 +0800" stop="20210515153000 +0800" channel="304">
    <title lang="en">Lucky Comes with Lion</title>
    <desc lang="en">Under the guidance of Master Fengshi, four little lions set out to use their superpowers to bring peace &amp; joy to their hometown, and spread optimism &amp; good values.(n)</desc>
  </programme>
```

**Comment by weareblahs** [comment]
It works. I'll refresh the EPG again.

Thanks!

**Comment by weareblahs** [comment]
Try refreshing it again.
