### ISSUE TITLE
How to use this with kodi?

### ISSUE THREAD

**Issue by pengilatbulan** [weareblahs/epg#3]
I try to use in epg remote and general section. But it is nor working.

**Comment by weareblahs** [comment]
You have to change the tvg-id on the playlist.

For example, change this line on your playlist from this:
#EXTINF:-1  tvg-logo="(Logo URL)",TV1
to this:
#EXTINF:-1 **tvg-id="101"** tvg-logo="(Logo URL)",TV1``

You must add tvg-id to your m3u8 playlist to make it working.

TVG-IDs are channel numbers, for example: 101 for TV1, 102 for TV2, etc.

**Comment by weareblahs** [comment]
It's not an error on your configuration (assuming you're using IPTV PVR Simple Client plugin). It's the problem of the playlist itself, and you have to change the tvg-id on your m3u8 playlist.

For example, change this line on your playlist from this:
#EXTINF:-1  tvg-logo="(Logo URL)",TV1
to this:
#EXTINF:-1 **tvg-id="101"** tvg-logo="(Logo URL)",TV1

You must add the channel tvg-id to your m3u8 playlist to make it working.

TVG-IDs are channel numbers, which can also be used as an identification for the channels, for example: 101 for TV1, 102 for TV2, etc.

You can also see the configuration files for the tvg-id ([here]()) to see which channels were available.
For example:
 ``    <channel update="i" site="astro.com.my" site_id="395" xmltv_id="101">TV1</channel>``
The ``xmltv_id="101"`` is the tvg-id for the channel.
