### ISSUE TITLE
Missing epg for berita RTM

### ISSUE THREAD

**Issue by callsignroy** [weareblahs/epg#5]
Hello, sorry for bothering..
I see that epg for berita rtm is missing since last commit on rtmklik.xml.

**Comment by weareblahs** [comment]
Change the tvg-id to RTMK04 (and other channels on RTM Klik too).

Here are the new changes to the tvg-ids:
- RTMK01: TV1
- RTMK02: TV2
- RTMK03: TV Okey
- RTMK04: Berita RTM
- RTMK05: TV Sukan (RTM Sports HD)
- RTMK06: TV6
- RTMK07: Dewan Rakyat
- RTMK08: Dewan Negara
