### ISSUE TITLE
New Channels EPG Source?

### ISSUE THREAD

**Issue by linkinstreet** [weareblahs/epg#9]
I see that the Unifi TV EPG is still using the old channels. I only rely on the free version of WebGrabPlus so I can't see the Unifi EPG scrapper since it's encrypted. But Singapore's singteltv is free, so I used that for Techstorm and GEM. the only issue I have is the EPG for GEM is in Chinese. 

Any plan to scrape Unifi for the new channels?

**Comment by weareblahs** [comment]
Will look on ***@***.*** for the new channel XML IDs for the channels
later.
